apply plugin: 'com.android.application'

android {
    namespace "com.tarik366.cont"
    compileSdk 35

    defaultConfig {
        applicationId "com.tarik366.cont"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                arguments "-DSDL_ANDROID=ON", "-DSDL_STATIC=ON"
                abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt" // Kök dizindeki ana CMakeLists'i kullanır
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}